### ISSUE TITLE
loginctl cannot lock own session

### ISSUE THREAD

**Issue by kensington** [andywingo/elogind#3]
$ loginctl lock-session c1
Failed to issue method call: Access denied

This looks like the same issue as systemd/systemd/issues/471, which was resolved with an update to org.freedesktop.login1.conf in systemd/systemd/pull/558.

The updated conf resolves the permission issue for me, but I wasn't able to get session locking to actually work yet (on a non-guix system).

**Comment by wingo** [comment]
Good catch!  I would be happy to merge a pull request to update the login1.conf :)

**Comment by kensington** [comment]
Sure, do you want the latest conf or just the changes in systemd/systemd#558?

**Comment by wingo** [comment]
No idea!  The smallest changes are easiest to say yes to, but if you think the latest conf is the right thing we can try that too.

**Comment by kensington** [comment]
I've created the PR based on the latest upstream login1.conf, excluding some entries that do not appear to correlate to anything in elogind. It works for me locally, but I'm not running guix.

**Comment by kensington** [comment]
Note that while most functions appear to work now, lock-sesion does not (but permission is no longer denied). I am unsure if exactly what the issue there is, so it would be interesting to know if `loginctl lock-session` works for a Guix user (Guix ships GNOME, right?).

**Comment by Yamakuzure** [comment]
I have patched various ebuilds so my gentoo system runs fine with elogind. I no longer get any errors when I try `loginctl lock-session <cnr>`, or any other message, but the locking does not work.

When I try, this pops up in `/var/log/messages`:

> `Nov 10 13:37:10 sed-notebook polkitd[16707]: Registered Authentication Agent for unix-process:21466:335831 (system bus name :1.96 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale de_DE.utf8)`
> `Nov 10 13:37:10 sed-notebook polkitd[16707]: Unregistered Authentication Agent for unix-process:21466:335831 (system bus name :1.96, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale de_DE.utf8) (disconnected from bus)`

I have patched polkit to support elogind, but maybe there is something missing.

On the other hand, though, does Plasma inhibit loginctl calls while it is in charge. At least as far as I know. So maybe it is completely in order for loginctl to not be able to forcefully lock or unlock otherwise fully functional sessions.

...maybe we're chasing a phantom here...

**Comment by kensington** [comment]
I've tested this with systemd proper in KDE neon and it does work, so I'm sure we're missing something but I've poked around too without luck. :-(

**Comment by Yamakuzure** [comment]
Ok, so no ghost hunt. At least this is good to know.

I have had fun this morning comparing the systemd/stable-v232 commit log with elogind. There is quite some catch-up to do.

Currently I am undecided about how to proceed. I have three ways in mind but am undecided. Hopefully I can mail you two my ideas today so we can discuss this. (GitHub doesn't have soem sort of project forums, does it?)

Well, it is not that difficult, it's just the way the systemd changes find their way into elogind that result in differences of certain details. Like keeping commit history or not and such things.

**Comment by wingo** [comment]
I doubt that a simple update would be beneficial FWIW -- it could take quite some time to sort out bugs, the mechanics of getting an update going are non-trivial if we want to keep history, and it isn't guaranteed to fix this particular bug..  If this issue is the important one for you probably it is more fruitful to look into the problem directly -- at least that way you're starting from a known state in other regards.

**Comment by kensington** [comment]
This is no longer an issue and works for me correctly in https://github.com/elogind/elogind/tree/dev_v226.
