### ISSUE TITLE
elogind gets into a suspend loop

### ISSUE THREAD

**Issue by jcjordyn130** [andywingo/elogind#6]
when I go into suspend/standby mode, it suspends but when I resume it wakes up then suspends again
I have to hard reset my pc

I'm using arch linux x64

**Comment by kensington** [comment]
I ran into this too, no idea of solution though.

**Comment by CameronNemo** [comment]
@kensington are you also running arch linux?

**Comment by kensington** [comment]
> @kensington are you also running arch linux?

@CameronNemo no, Gentoo

**Comment by udeved** [comment]
@CameronNemo 

Do you eventually use this [build](https://github.com/manjaro/packages-openrc/tree/master/elogind)?

If so, the pkgbuild is just playground, nothing to use on a productive system, and the elogind version produces some troubles.

**Comment by jcjordyn130** [comment]
@udevd I use this package [https://aur.archlinux.org/packages/elogind-git/](https://aur.archlinux.org/packages/elogind-git/)

**Comment by Yamakuzure** [comment]
elogind takes over suspension. If you have another tool to do that, like powerdevil, laptop-mode-tools, acpitools, whatever-tools, they get in each other ways.
Just tell elogind to ignore suspend commands in /etc/elogind/logind.conf

**Comment by jcjordyn130** [comment]
I don't have any other tools to manage suspend

**Comment by Yamakuzure** [comment]
@jcjordyn130 Then what kind of system are you using? Which init system? Which DE/WM?

**Comment by jcjordyn130** [comment]
system? as in? I'm using minirc and plasma 5 with elogind of course

**Comment by Yamakuzure** [comment]
@jcjordyn130 I am asking, because your details so far where limited at best.
However, lets try to get to the bottom of this.

The main reason for a suspend loop is two "systems" thrashing into each others legs.

Example:
When I first installed elogind on my system (Gentoo/openrc/Plasma 5) I got a suspend loop, because the default installation uses ConsoleKit2 as session tracker.
PowerDevil, fully aware that Plasma was started through ck-launch-session, caught the suspend signal, and asked CK whether this was in order.
In the meantime elogind had already decided that suspension would be fine and put my laptop to sleep.
After resuming, the woken up processes around PowerDevil simply continued their work on putting my laptop into suspension.

The first fix for me was to change the file /etc/elogind/logind.conf

From:

> `#HandlePowerKey=poweroff`
> `#HandleSuspendKey=suspend`
> `#HandleHibernateKey=hibernate`
> `#HandleLidSwitch=suspend`

To:

> `HandlePowerKey=ignore`
> `HandleSuspendKey=ignore`
> `HandleHibernateKey=ignore`
> `HandleLidSwitch=ignore`

After I got rid of ConsoleKit2, I switched back to the defaults and everything is working fine now.

So if you change said file to make elogind ignore these events, restart your system, and find that you can suspend normally again, you have something getting into elogind's way. Get rid of it and you can have elogind do its job.

Important: Having more than one session tracker at the same time is a very bad idea.
So use either "ConsoleKit2" OR "systemd-logind" OR "elogind".

**Comment by Yamakuzure** [comment]
This issue is fixed in the v226.4 release at elogind/elogind, so this issue can be closed.
